definitions:
  apihelpers.ApiResponse:
    properties:
      data: {}
      message:
        type: string
      status:
        type: boolean
    type: object
  models.CreateAndUpdateTaskReq:
    properties:
      assigneeId:
        type: string
      description:
        type: string
      dueDate:
        type: string
      priority:
        type: string
      status:
        type: string
      title:
        type: string
    required:
    - assigneeId
    - description
    - dueDate
    - priority
    - status
    - title
    type: object
  models.CreateProjectReq:
    properties:
      description:
        type: string
      name:
        type: string
    required:
    - name
    type: object
  models.UpdateProjectReq:
    properties:
      description:
        type: string
      name:
        type: string
    required:
    - name
    type: object
  models.UserAuthRes:
    properties:
      email:
        type: string
      token:
        type: string
      userId:
        type: string
    type: object
  models.UserLogin:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  models.UserRegister:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: User Login
      parameters:
      - description: User Login Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/models.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/apihelpers.ApiResponse'
            - properties:
                data:
                  $ref: '#/definitions/models.UserAuthRes'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: User Registration
      parameters:
      - description: User Registration Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/models.UserRegister'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/apihelpers.ApiResponse'
            - properties:
                data:
                  $ref: '#/definitions/models.UserAuthRes'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
      tags:
      - auth
  /projects:
    get:
      consumes:
      - application/json
      description: Get All Projects
      parameters:
      - description: Authorization Header
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
      tags:
      - projects
    post:
      consumes:
      - application/json
      description: Create Project
      parameters:
      - description: Authorization Header
        in: header
        name: Authorization
        required: true
        type: string
      - description: Create Project Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/models.CreateProjectReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
      tags:
      - projects
  /projects/{projectId}:
    delete:
      consumes:
      - application/json
      description: Delete Project By Id
      parameters:
      - description: Authorization Header
        in: header
        name: Authorization
        required: true
        type: string
      - description: Project Id
        in: path
        name: projectId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
      tags:
      - projects
    get:
      consumes:
      - application/json
      description: Get Project By Id
      parameters:
      - description: Authorization Header
        in: header
        name: Authorization
        required: true
        type: string
      - description: Project Id
        in: path
        name: projectId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
      tags:
      - projects
    patch:
      consumes:
      - application/json
      description: Update Project By Id
      parameters:
      - description: Authorization Header
        in: header
        name: Authorization
        required: true
        type: string
      - description: Project ID
        in: path
        name: projectId
        required: true
        type: string
      - description: Update Project Payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.UpdateProjectReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
      tags:
      - projects
  /projects/{projectId}/tasks:
    get:
      consumes:
      - application/json
      description: Get All Tasks By Project Id
      parameters:
      - description: Authorization Header
        in: header
        name: Authorization
        required: true
        type: string
      - description: Project ID
        in: path
        name: projectId
        required: true
        type: string
      - description: Status
        in: query
        name: status
        type: string
      - description: Assignee ID
        in: query
        name: assignee_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
      tags:
      - task
    post:
      consumes:
      - application/json
      description: Create Task using project id
      parameters:
      - description: Authorization Header
        in: header
        name: Authorization
        required: true
        type: string
      - description: Project ID
        in: path
        name: projectId
        required: true
        type: string
      - description: Create Task Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/models.CreateAndUpdateTaskReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
      tags:
      - task
  /tasks/{taskId}:
    delete:
      consumes:
      - application/json
      description: Delete Task By Id
      parameters:
      - description: Authorization Header
        in: header
        name: Authorization
        required: true
        type: string
      - description: Task ID
        in: path
        name: taskId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
      tags:
      - task
    get:
      consumes:
      - application/json
      description: Get Task By Id
      parameters:
      - description: Authorization Header
        in: header
        name: Authorization
        required: true
        type: string
      - description: Task ID
        in: path
        name: taskId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
      tags:
      - task
    patch:
      consumes:
      - application/json
      description: Update Task By Id
      parameters:
      - description: Authorization Header
        in: header
        name: Authorization
        required: true
        type: string
      - description: Task ID
        in: path
        name: taskId
        required: true
        type: string
      - description: Update Task Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CreateAndUpdateTaskReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apihelpers.ApiResponse'
      tags:
      - task
swagger: "2.0"
